apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: soiree
data:
  DB_HOST: "database-1.cfmmi4iqyrkp.ap-southeast-1.rds.amazonaws.com"  
  DB_NAME: "webdb"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka-service:9092"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  NOTIFY_URL: "https://ivv0231b88.execute-api.ap-southeast-1.amazonaws.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: soiree
type: Opaque
stringData:
  DB_USER: "admin"
  DB_PASS: "admin123"   
